esphome:
  name: ivt-temp-controller
  friendly_name: IVT Temperature Controller

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "2+wvDiHuDVqm4e49Xumm2BRZRQr7JCrO/5T4ENsQLRk="

ota:
  - platform: esphome
    password: "9c5126b852b2be8de2f821782907f22c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ivt-Temp-Controller"
    password: "qiU68Sjoziep"

captive_portal:
    
spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13

# declaration of external component
external_components:
  - source: 
      type: git
      url: http://github.com/MartinOlaussons/MCP41010-ESPHome

# MCP41010
mcp41010:
  id: my_pot
  cs_pin: GPIO15

# Relä till IVT utetemp-ingång
switch:
  - platform: gpio
    pin: D1
    name: "IVT Temp Tweaker Relay"
    restore_mode: ALWAYS_OFF

# Slider i Home Assistant som styr MCP41100 via lambda
number:
  - platform: template
    name: "IVT DigiPot"
    id: digipot_level
    optimistic: true
    min_value: 0
    max_value: 255
    initial_value: 0
    step: 1
    mode: slider
    on_value:
      then:
        - lambda: |-
            id(my_pot).set_value(id(digipot_level).state);

