esphome:
  name: ivt-temp-controller
  friendly_name: ivt-temp-controller

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "2+wvDiHuDVqm4e49Xumm2BRZRQr7JCrO/5T4ENsQLRk="

ota:
  - platform: esphome
    password: "9c5126b852b2be8de2f821782907f22c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ivt-Temp-Controller"
    password: "qiU68Sjoziep"

captive_portal:
    
spi:
  clk_pin: D5
  mosi_pin: D7
  miso_pin: D6  # valfritt, MCP41100 behöver egentligen inte MISO
  id: spi_bus

# Relä till IVT utetemp-ingång
switch:
  - platform: gpio
    pin: D1
    name: "IVT Temp Tweaker Relay"
    restore_mode: ALWAYS_OFF

# Slider i Home Assistant som styr MCP41100 via lambda
number:
  - platform: template
    name: "IVT DigiPot"
    min_value: 0
    max_value: 100
    step: 1
    set_action:
      - lambda: |-
          uint8_t value = (uint8_t)((x / 100.0) * 255.0);  // 0-100 -> 0-255
          digitalWrite(D8, LOW); 
          SPI.transfer(0x11);  // MCP41100: write to pot0
          SPI.transfer(value);
          digitalWrite(D8, HIGH);

